### ISSUE TITLE
minor improvements

### ISSUE THREAD

**Issue by Pooja3894** [niwa/geoapis#23]
- Warning if no data in a polygon
- print out error missing f string: "The geometry_name's tried are: +{geometry_type_list}" 
- if the boundary polygon CRS is None set it using CRS

**Comment by rosepearson** [comment]
- change the assertion in https://github.com/niwa/geoapis/blob/main/src/geoapis/lidar.py#L177 with raising an exception. 

Assertions are good but in general used enforce some invariants (eg. a condition that should never be reached if the code is properly used). Here this is more like a test so an exception looks, to me, more appropriate. From Maxime

**Comment by rosepearson** [comment]
- Ensure that geoapis can handle the case that a multipolgon is passed as a bounding polygon - or at least that a useful error message is returned. This is a problem from the raster module. Not sure about the vector module. 

![image](https://user-images.githubusercontent.com/22883860/204403351-7e8e8c2e-f383-4f8c-a66e-84568347068e.png)
